# Generated by Django 4.0.6 on 2022-08-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_blog_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='picture',
            field=models.ImageField(help_text='Here you can attach image', upload_to='main/static/main/media', verbose_name='Picture'),
        ),
    ]
