# Generated by Django 4.0.6 on 2022-08-11 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_blog_data_alter_blog_picture_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
