# Generated by Django 4.0.6 on 2022-08-11 13:02

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(django.contrib.auth.models.User), to=settings.AUTH_USER_MODEL),
        ),
    ]
