# Generated by Django 4.0.6 on 2022-08-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
