# Generated by Django 4.0.6 on 2022-08-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(null=True),
        ),
    ]
