# Generated by Django 4.0.6 on 2022-08-27 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_profile_bio_alter_profile_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-data']},
        ),
    ]
